### ISSUE TITLE
Swipe to the left

### ISSUE THREAD

**Issue by rafahead** [Magnuti/Weekly-Date-Picker#1]
Yours widget is fantastic. Congrats.

It's not possible to swipe to the left and get the date before the select day?

thanks

**Comment by Magnuti** [comment]
Thank you! It is not possible to swipe left at the moment, but the functionality has been considered. I agree that it should be possible to swipe left. I can try to implement it this week, or you can make a PR if you need it right now.

**Comment by rafahead** [comment]
Thanks for the feedback. I tried to modify it, you are using an infinite pageview and I couldn't find the best solution.

**Comment by Magnuti** [comment]
The functionality has now been added to version 1.3.0. https://pub.dev/packages/weekly_date_picker/versions/1.3.0
