### ISSUE TITLE
Can you possibly show the month name

### ISSUE THREAD

**Issue by Govindbetterlives** [Magnuti/Weekly-Date-Picker#3]
Hi,
Can you possibly show the month name.

**Comment by Magnuti** [comment]
It is possible to place your own month name in your Flutter application where ever you want. For example, if you want the month name above the month picker you could write something like this

```dart
Column(
  children: [
    Text(_selectedDay.month),
    WeeklyDatePicker(
      selectedDay: _selectedDay, // DateTime
      changeDay: (value) => setState(() {
        _selectedDay = value;
      }),
    ),
  ]
)
```

Placing the month name in the `WeeklyDatePicker` widget is out of the scope of this package.
