### ISSUE TITLE
missing borderColor

### ISSUE THREAD

**Issue by blandinf** [Magnuti/Weekly-Date-Picker#7]
borderColor is always white, is it possible to add a property to update it? Thanks!

**Comment by Magnuti** [comment]
Yes that seems possible! I am working on a fix right now @blandinf

**Comment by Magnuti** [comment]
Is this the border you mean @blandinf?

![IMG_3627AC116D23-1](https://github.com/Magnuti/Weekly-Date-Picker/assets/43852515/6a975cc9-80a0-4b51-80f5-e4a2aa0af0cd)

**Comment by blandinf** [comment]
Yes!

**Comment by Magnuti** [comment]
Adding custom border color has been added to the newest version 1.4.2 https://pub.dev/packages/weekly_date_picker/versions/1.4.2 @blandinf. Just add

```dart
selectedDigitBorderColor = const Color(<your color code>)
```

Thank you for the issue!

**Comment by blandinf** [comment]
top thank you! 
is it possible to also add unselectedDigitBorderColor? 🙄
Have a good day!
